---

- name: install OpenHPC repository
  yum:
    name: "{{ munge_ohpc_version }}"
  tags: slurm

- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - slurm-munge-ohpc
  tags: slurm

- name: create Munge key
  copy:
    content: "{{ munge_key }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600
  notify: restart munge
  no_log: true
  tags: slurm

- name: start and enable Munge
  service:
    name: munge
    state: started
    enabled: yes
  tags: slurm
